### PR TITLE
Remove files used by Docker Image build

### PR DESCRIPTION
**Pull request by aditya-konarde**
We're pulling the images from registry.centos.

### CODE REVIEW

**Comment by syamgk** [comment]
LGTM

**Comment by aditya-konarde** [comment]
Do not merge yet. Needs discussion for the workflow we follow going forward.

**Comment by aditya-konarde** [comment]
@syamgk we can merge this.

**Comment by kbsingh** [comment]
is the process confirmed at this point ? are we good to merge and close this off ?

**Comment by aditya-konarde** [comment]
@kbsingh this can be merged.

**Comment by syamgk** [comment]
LGTM

**Comment by aditya-konarde** [comment]
[test]

**Comment by aditya-konarde** [comment]
@syamgk we're good to merge this now.

**Pull request merged**
